### PR TITLE
Introducing Linter, changing to better variables, removing redundant variables

### PR DESCRIPTION
**Pull request by maxspahn**
Clears variable, adds documentation and introduces linting.

### CODE REVIEW

**Comment by maxspahn** [comment]
/remind me to review motion planning scenes PR tomorrow

**Comment by maxspahn** [comment]
@GijsGroote You might look at this, too see whether you approve of these changes.

**Comment by GijsGroote** [comment]
I will take a look asap, which is next monday

**Review by GijsGroote — APPROVED** [review]
Ah, this helps me learn how this repo is intended to work. I do not yet have a large opinion on the commits you've created here because I am still in a learning phase for this one.

**Pull request merged**
